const translations = {
      ru: {
        "hero-title": "Добро пожаловать в Mykhalova Massage",
        "hero-text": "Ваше тело говорит — я умею его слушать.",
        "hero-btn": "Записаться сейчас ✅",
        "about": "Кто я",
        "about-text": "Меня зовут Ирина, я профессиональный массажист и специалист по телесной терапии...",
        "about-text2": "В работе я использую сочетание классического, глубокотканного и фасциального массажа...",
        "about-text3": "Каждый сеанс — индивидуальный подход, внимание к деталям и забота о вашем здоровье.",
        "services": "Услуги",
        "service1-title": "Классический массаж",
        "service1-text": "Снимает мышечное напряжение и улучшает общее самочувствие.",
        "service2-title": "Глубокотканный массаж",
        "service2-text": "Прорабатывает глубокие слои мышц и фасций...",
        "service3-title": "Фасциальный массаж",
        "service3-text": "Восстанавливает подвижность тканей и помогает скорректировать осанку.",
        "service4-title": "Антистресс-массаж",
        "service4-text": "Снимает психоэмоциональное напряжение и восстанавливает энергию.",
        "service5-title": "Терапевтический массаж",
        "service5-text": "По диагностике тела находит истинную причину боли и создаёт индивидуальный план.",
        "service6-title": "Массаж для спортсменов",
        "service6-text": "Подготовка мышц к нагрузкам и восстановление после тренировок.",
        "service7-title": "Лимфодренажный массаж",
        "service7-text": "Эффективен при отёках и нарушениях лимфотока, ускоряет восстановление.",
        "service8-title": "Глубокий массаж лица",
        "service8-text": "Естественный лифтинг, уменьшение отёков и улучшение тонуса кожи.",
        "service9-title": "Детский терапевтический массаж",
        "service9-text": "Мягкая работа с телом ребёнка для снятия напряжения и коррекции осанки.",
        "approach": "Как я работаю",
        "approach-intro": "Моя работа строится поэтапно, чтобы найти причину боли и вернуть лёгкость движений.",
        "step1": "Начинаю с диагностики тела (анализ постуры, мышечного баланса, фасций).",
        "step2": "Работаю не только там, где болит, а с причиной проблемы.",
        "step3": "Использую сочетание разных техник: глубокие, мягкие, фасциальные, кинезиологические.",
        "step4": "Даю домашние упражнения для закрепления результата.",
        "step5": "Гарантирую индивидуальный и безопасный подход к каждому клиенту.",
        "contact": "Контакты",
        "contact-text": "Свяжитесь со мной для записи на сеанс массажа",
        "about-hero": "«Ваше тело говорит — я умею его слушать.»",
        "about-intro": "Меня зовут Ирина, и моя работа — переводить язык вашего тела в лёгкость и свободу.",
        "about-quote": "Я массажист с медицинским образованием, но главное — я человек, который верит, что боль и напряжение не должны управлять нашей жизнью.",
        "about-journey-intro": "Каждый сеанс для меня — это путешествие:",
        "list1":"из зажима — к движению",
        "list2":"из усталости — к энергии",
        "list3":"из тяжести — к ощущению «я снова в своём теле»",
        "about-method": "Я соединяю науку и интуицию: знания анатомии и физиологии с вниманием к тому, что именно сейчас нужно вашему телу. Массаж становится не просто техникой, а диалогом: я слушаю мышцы, фасции, дыхание, и вместе с вами мы находим путь к равновесию.",
        "about-invite": "🌿 Если ваше тело устало, болит или просто просит заботы — приходите. Я помогу ему вспомнить, что значит быть живым, лёгким и сильным.",
        "about-f1-title": "Диагностика",
        "about-f1-text": "Анализ осанки, мышечного баланса и фасций перед началом работы.",
        "about-f2-title":"Комбинация техник",
        "about-f2-text": "Классический, глубокотканный, фасциальный, кинезиологические приёмы.",
        "about-f3-title":"Домашние упражнения",
        "about-f3-text":"Короткие протоколы для закрепления эффекта и профилактики боли.",
     
     
     
      },
      en: {
        "hero-title": "Welcome to Mykhalova Massage",
        "hero-text": "Relieve tension, restore energy, and bring harmony to yourself",
        "hero-btn": "Book Now ✅",
        "about": "Who I Am",
        "about-text": "My name is Irina, I am a professional massage therapist and bodywork specialist...",
        "about-text2": "I combine classical, deep tissue, and fascial massage techniques with body diagnostics...",
        "about-text3": "Every session is tailored to you, with attention to detail and care for your well-being.",
        "services": "Services",
        "service1-title": "Classical Massage",
        "service1-text": "Relieves muscle tension and improves overall well-being.",
        "service2-title": "Deep Tissue Massage",
        "service2-text": "Works on deep muscle layers and fascia, helps relieve chronic tension.",
        "service3-title": "Fascial Massage",
        "service3-text": "Restores tissue mobility and improves posture.",
        "service4-title": "Anti-Stress Massage",
        "service4-text": "Relieves emotional tension and restores energy.",
        "service5-title": "Therapeutic Massage",
        "service5-text": "Identifies the root cause of pain using body diagnostics.",
        "service6-title": "Sports Massage",
        "service6-text": "Prepares muscles for activity and aids recovery.",
        "service7-title": "Lymphatic Drainage Massage",
        "service7-text": "Reduces swelling and accelerates recovery.",
        "service8-title": "Deep Facial Massage",
        "service8-text": "Natural lifting and improves skin tone.",
        "service9-title": "Children’s Massage",
        "service9-text": "Gentle work to relieve tension and correct posture.",
        "approach": "How I Work",
        "approach-intro": "My work is structured in steps to find the root cause of pain and restore ease of movement.",
        "step1": "Start with body diagnostics (posture, muscle balance, fascia analysis).",
        "step2": "Treat the root cause of pain, not just symptoms.",
        "step3": "Combine different techniques: deep, soft, fascial, kinesiology.",
        "step4": "Provide home exercises to maintain results.",
        "step5": "Individual and safe approach for every client.",
        "contact": "Contacts",
        "contact-text": "Get in touch to book a massage session",
        "about-hero": "«Your body speaks — I know how to listen to it.»",
        "about-intro": "My name is Irina, and my work is to translate the language of your body into lightness and freedom.",
        "about-quote": "I am a massage therapist with a medical background, but above all — a person who believes that pain and tension should not control our lives.",
        "about-journey-intro":"Each session for me is a journey:",
        "list1":"from tension — to movement",
        "list2":"from fatigue — to energy",
        "list3":"from heaviness — to the feeling of 'I am back in my body'",
        "about-method": "I combine science and intuition: knowledge of anatomy and physiology with attention to what your body needs right now. Massage becomes more than just a technique — it is a dialogue: I listen to your muscles, fascia, and breath, and together with you we find the path to balance.",
        "about-invite": "🌿 If your body is tired, in pain or simply asking for care — come. I will help it remember what it means to be alive, light and strong.",
        "about-f1-title":"Diagnostics",
        "about-f1-text":"Posture, muscle balance and fascia assessment before the session.",
        "about-f2-title": "Technique Mix",
        "about-f2-text": "Classical, deep tissue, fascial and kinesiology methods.",
        "about-f3-title":"Home Practice",
        "about-f3-text": "Short routines to maintain results and prevent pain.",

      }
    };

    function setLang(lang) {
      document.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.getAttribute('data-lang');
        if(translations[lang][key]){
          el.textContent = translations[lang][key];
        }
      });
    }
