name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     - uses: peaceiris/actions-gh-pages@v4.4.2

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
